### PR TITLE
Refactor to use space, fontSize, lineHeight and radii from theme

### PR DESCRIPTION
**Pull request by KenanYusuf**
Adds space, fontSize, lineHeight and radii to the theme and apply properties across the application.

## Relative units

I have updated all of the fixed widths, heights, font sizes, line heights, padding and margin values to use relative units (`rem`) instead of `px`. This [article](https://www.24a11y.com/2019/pixels-vs-relative-units-in-css-why-its-still-a-big-deal/) does a good job of explaining why it's still worthwhile doing this. **TLDR**: using relative units takes into account the user's preferred font size and scales appropriately. The only property that I haven't updated to use relative units is `border` as it doesn't need to scale. 

## Space

Adds a spacing scale to be used when setting `padding` and `margin` values. Each index increments slightly. Each spacing value is applied to a key rather than in an array - this helps when scanning the theme for the value that you want, as you can reference the key instead of counting how far the value is from the first index.

```ts
{
  space: {
    0: 0,
    1: rem(2),
    2: rem(4),
    3: rem(8),
    4: rem(12),
    5: rem(16),
    6: rem(20),
    7: rem(24),
    8: rem(32),
    9: rem(48),
    10: rem(64),
  },
}
```

```ts
const Title = styled.h2`
  margin-bottom: ${p => p.theme.space[4]};
`;
```

## Radii

Added a radii object to maintain consistent `border-radius` across the project.

```ts
{
  radii: {
    s: rem(2),
    m: rem(4),
    round: "50%",
  }
}
```

```ts
const Box = styled.div`
  border-radius: ${p => p.radii.m};
`;
```

## Font size & line height

Added fontSizes and lineHeights objects with the frequently used sizes. Each line height property is ~120% of the corresponding font size.

```ts
{
  fontSizes: {
    body: {
      s: rem(11),
      m: rem(12),
      l: rem(13),
      xl: rem(16),
    },
    display: {
      s: rem(40),
      m: rem(60),
      l: rem(80),
    },
  },
  lineHeights: {
    body: {
      s: rem(14),
      m: rem(15),
      l: rem(16),
      xl: rem(20),
    },
    display: {
      s: rem(48),
      m: rem(72),
      l: rem(96),
    },
  }
}
```

```ts
const Title = styled.h2`
  font-size: ${p => p.theme.fontSizes.body.xl};
  line-height: ${p => p.theme.lineHeights.body.xl};
`;
```

### CODE REVIEW

**Comment by andyrichardson** [comment]
Looks good! 

Particularly a fan of the typography sizes!

I'm not totally sure about the use of _rem_ units in devtools panels or electron. In theory it will just get computed to _pixel_ units at runtime (pre viewport scaling + rasterisation) but it's something worth testing ahead of time because I'm not sure if we'll see consistent results across environments (electron, firefox, chrome, cosmos)

**Comment by KenanYusuf** [comment]
@andyrichardson From testing on just Chrome, it seems to be working as expected:

Set my preferred font size to very large:

Screenshot 2021-05-10 at 11 26 40

**Without** relative units:

Screenshot 2021-05-10 at 11 24 38

**With** relative units:

Screenshot 2021-05-10 at 11 24 19

I guess the bigger question is **should developer tools respect a user's font size preference?** From testing, Chrome's developer tools **do not**. Interested in people's thoughts on this - my instincts say if someone has difficulty reading websites generally, then they will also have difficulty reading small/large text in a developer tool.

Either way, easy enough to remove this if we get a consensus that it's not worth using `rem`

**Comment by KenanYusuf** [comment]
@andyrichardson did a bit more research on this - seems the best practice is to size everything using relative units **except** from UI elements that should not scale i.e. borders (including pane spitters in our case).

To help conceptualise it I tested both scenarios:

| Spacing as `px` | Spacing as `rem` |
| - | - |
| space-not-relative |  space-relative |

My feeling is that the `px` based spacing makes the layout look cramped when font size is scaled up, but happy to hear other opinions on this!

Great point on the virtual canvas bits. Done some more testing on each area of the app and the only scaling based issue I came across was with tooltip positioning which I've fixed here https://github.com/FormidableLabs/urql-devtools/pull/360/commits/dbcd8c54827709b9a78dfe796d2698370e9d244d. Pane resizing and scrolling works as expected 🎉

**Review by wgolledge — APPROVED** [review]
Thanks for the super descriptive/informative PR description!

Everything here makes a lotta sense to me and it's awesome how everything is now conforming to the theme. 

The only comment I have is that I think the change in bg colour makes it a bit harder to distinguish between the timeline & events.

**Pull request merged**
