### PR TITLE
(feat) - headers for devtools

### PR DESCRIPTION
**Pull request by JoviDeCroock**
When trying out the developer tools I missed a bit of information because I know urql internals I know what these variables are but I think for a beginner this can be confusing so I added Headers.

These look like:

Screenshot 2019-08-05 at 11 05 09

Screenshot 2019-08-05 at 11 05 16

### CODE REVIEW

**Comment by andyrichardson** [comment]
Looks great! 

How do you feel about leaving out the headers in the collapsed view?

**Comment by JoviDeCroock** [comment]
@andyrichardson I'd be okay with that personally

**Comment by JoviDeCroock** [comment]
How it looks without headers in small sized devtools screen

Screenshot 2019-08-05 at 11 43 11

On the side, is it normal that `sailci/install`script isn't running?

**Comment by andyrichardson** [comment]
> On the side, is it normal that sailci/installscript isn't running?

At the moment yeah 🤷‍♂

**Pull request merged**
