### PR TITLE
Remove truncation on the explorer view

### LINKED ISSUE #287: Remove truncation on the exporer view
On the explorer view, some of the data gets truncated regardless of how much space there is to display it. It’s be great to see the whole JSON, or at the very least have an option to expand to see everything.

Screenshot 2020-08-18 at 12 04 14

### PR DESCRIPTION
**Pull request by Rigellute**
Closes #287

This might be a heavy handed fix (removes the `trimCode` function). Perhaps I lack context on why the truncation was there in the first place?

Seems like we might as well just show all the json? Unless there is a reason not too?

### CODE REVIEW

**Comment by andyrichardson** [comment]
@Rigellute thanks for this - looking at the screenshot in the issue, getting rid of truncation is a good shout!

> why the truncation was there in the first place?

The truncation isn't ideal and was a fix for (#76). Ideally we would have arguments wrapping but that's a little tricky at the moment because the containing element uses a fixed height. It's not super obvious but in the meantime, the query arguments come up in the info panel when expanding a row.

**Review by andyrichardson — APPROVED** [review]

**Comment by andyrichardson** [comment]
Non blocking - if you have a moment, we could do with renaming the [fixtures here](https://github.com/FormidableLabs/urql-devtools/blob/fb053cff8779cb8ba0dd83bb185ce4ed40f54af5/src/panel/components/CodeHighlight.fixture.tsx) to use something other than "collapsed" for larger examples now that they're not being collapsed.

**Comment by Rigellute** [comment]
@andyrichardson I could rename "collapsed" to "large"?

**Comment by andyrichardson** [comment]
> @andyrichardson I could rename "collapsed" to "large"?

@Rigellute yeah that should do it 👍

**Comment by Rigellute** [comment]
Updated the fixture naming 👍

**Pull request merged**
